(function(){'use strict';
var $$=function(s){return[].slice.call(document.querySelectorAll(s))};
function url(p){return !p?'':(/^(https?:)?\//.test(p)?p:'/'+p)}
function j(u){return fetch(u).then(function(r){if(!r.ok)throw 0;return r.json()})}
function rub(n){return Math.round(n).toLocaleString('ru-RU')+'\u00a0₽'}
j('/api/media').then(function(d){var m=(d.media||[]),pick=function(g){return m.filter(function(x){return x.group===g}).sort(function(a,b){return(a.sort_order||0)-(b.sort_order||0)})};var list=pick('hero').concat(pick('kuzar'),pick('lava'));$$('.art .ph img').forEach(function(im,i){var x=list[i];if(x&&url(x.path)!==im.getAttribute('src')){var n=new Image();n.onload=function(){im.src=n.src;im.alt=x.alt||''};n.src=url(x.path)}})}).catch(function(){});
j('/api/catalog').then(function(d){var p=(d.categories||[]).filter(function(c){return c.kind==='package'})[0];if(!p)return;var v=p.items.map(function(i){return Math.min(i.price_weekday||1e9,i.price_weekend||1e9)}).filter(function(x){return x<1e9});if(v.length)$$('[data-minprice]').forEach(function(e){e.textContent='от '+rub(Math.min.apply(null,v))})}).catch(function(){});
j('/api/settings').then(function(d){var c=(d.settings||{}).contacts||{};if(c.phone)$$('[data-phone]').forEach(function(e){e.textContent=c.phone;e.href='tel:'+c.phone.replace(/[^\d+]/g,'')});if(c.hours)$$('[data-hours]').forEach(function(e){e.textContent=c.hours})}).catch(function(){});
var RM=matchMedia('(prefers-reduced-motion: reduce)').matches;
function confetti(x,y){if(RM)return;var cv=document.createElement('canvas');cv.id='fx';document.body.appendChild(cv);var d=Math.min(devicePixelRatio||1,1.5),W=innerWidth,H=innerHeight;cv.width=W*d;cv.height=H*d;cv.style.width=W+'px';cv.style.height=H+'px';var c=cv.getContext('2d');c.scale(d,d);var C=['#ff3b30','#ffc23d','#3d7bff','#22c58b','#ff5fa2','#ff6a3d'],P=[];for(var i=0;i<110;i++){var a=-Math.PI/2+(Math.random()-.5)*2.2,s=7+Math.random()*9;P.push({x:x,y:y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,w:6+Math.random()*6,h:4+Math.random()*5,r:Math.random()*6,vr:(Math.random()-.5)*.35,c:C[i%6]})}var t0=performance.now();(function f(t){var k=(t-t0)/1700;c.clearRect(0,0,W,H);c.globalAlpha=Math.max(0,1-k*k);P.forEach(function(p){p.vy+=.32;p.vx*=.985;p.vy*=.985;p.x+=p.vx;p.y+=p.vy;p.r+=p.vr;c.save();c.translate(p.x,p.y);c.rotate(p.r);c.fillStyle=p.c;c.fillRect(-p.w/2,-p.h/2,p.w,p.h*Math.abs(Math.cos(p.r*2)));c.restore()});if(k<1)requestAnimationFrame(f);else cv.remove()})(t0)}
document.addEventListener('click',function(e){var b=e.target.closest('[data-book]');if(!b)return;var r=b.getBoundingClientRect();confetti(r.left+r.width/2,r.top+r.height/2)});
})();
