insert into site_settings(key,value) values('contacts','{"addressShort": "Балканская ул., 17", "addressFull": "Балканская улица, 17, ТРК «Балкания Nova», 3 этаж", "phone": "+7 981 818-01-34", "hours": "10:00–22:00", "mapQuery": "Санкт-Петербург, Балканская улица, 17", "mapLat": 59.8252, "mapLon": 30.3808}') on conflict (key) do update set value=excluded.value;
insert into site_settings(key,value) values('ages','{"kuzar": 7, "lavaFloor": 4}') on conflict (key) do update set value=excluded.value;
insert into site_settings(key,value) values('tiers','{"timeCards30": 1290, "timeCards60": 2190, "unlimitedWeekday": 1500, "unlimitedWeekend": 1800}') on conflict (key) do update set value=excluded.value;
insert into site_settings(key,value) values('rooms','{"extendOne": 2500, "extendTwo": 5000}') on conflict (key) do update set value=excluded.value;
insert into site_settings(key,value) values('extras','{"azot": 13000, "neon": 10000, "bubbles": 10000, "challenge": 8500, "pinata": 4000, "masterclass": 10000, "quest": 8000, "animator": 8000, "magician": 15000}') on conflict (key) do update set value=excluded.value;
insert into categories(slug,title,sort_order) values('packs','Пакеты',1) on conflict (slug) do nothing;
insert into products(category_id,slug,title,price_weekday,price_weekend,sort_order) select id,'malysh','Малыш',24500,24500,0 from categories where slug='packs' on conflict (slug) do update set price_weekday=excluded.price_weekday;
insert into products(category_id,slug,title,price_weekday,price_weekend,sort_order) select id,'jungle','Джунгли',33000,33000,1 from categories where slug='packs' on conflict (slug) do update set price_weekday=excluded.price_weekday;
insert into products(category_id,slug,title,price_weekday,price_weekend,sort_order) select id,'king','Королевский',50500,50500,2 from categories where slug='packs' on conflict (slug) do update set price_weekday=excluded.price_weekday;
insert into products(category_id,slug,title,price_weekday,price_weekend,sort_order) select id,'cyber','Кибер',36500,36500,3 from categories where slug='packs' on conflict (slug) do update set price_weekday=excluded.price_weekday;
insert into galleries(slug,title) values('collage','collage') on conflict (slug) do nothing;
insert into media(storage_path,folder,alt) values('hero/hero-collage-1.jpg','hero','') on conflict (bucket,storage_path) do nothing;
insert into gallery_media(gallery_id,media_id,sort_order) select g.id,m.id,0 from galleries g, media m where g.slug='collage' and m.storage_path='hero/hero-collage-1.jpg' on conflict do nothing;
insert into media(storage_path,folder,alt) values('hero/hero-collage-2.jpg','hero','') on conflict (bucket,storage_path) do nothing;
insert into gallery_media(gallery_id,media_id,sort_order) select g.id,m.id,1 from galleries g, media m where g.slug='collage' and m.storage_path='hero/hero-collage-2.jpg' on conflict do nothing;
insert into media(storage_path,folder,alt) values('hero/hero-collage-3.jpg','hero','') on conflict (bucket,storage_path) do nothing;
insert into gallery_media(gallery_id,media_id,sort_order) select g.id,m.id,2 from galleries g, media m where g.slug='collage' and m.storage_path='hero/hero-collage-3.jpg' on conflict do nothing;
insert into media(storage_path,folder,alt) values('hero/hero-collage-4.jpg','hero','') on conflict (bucket,storage_path) do nothing;
insert into gallery_media(gallery_id,media_id,sort_order) select g.id,m.id,3 from galleries g, media m where g.slug='collage' and m.storage_path='hero/hero-collage-4.jpg' on conflict do nothing;
insert into media(storage_path,folder,alt) values('hero/hero-collage-5.jpg','hero','') on conflict (bucket,storage_path) do nothing;
insert into gallery_media(gallery_id,media_id,sort_order) select g.id,m.id,4 from galleries g, media m where g.slug='collage' and m.storage_path='hero/hero-collage-5.jpg' on conflict do nothing;
insert into media(storage_path,folder,alt) values('hero/hero-collage-6.jpg','hero','') on conflict (bucket,storage_path) do nothing;
insert into gallery_media(gallery_id,media_id,sort_order) select g.id,m.id,5 from galleries g, media m where g.slug='collage' and m.storage_path='hero/hero-collage-6.jpg' on conflict do nothing;
insert into media(storage_path,folder,alt) values('rooms/jungle/room-jungle-1.jpg','rooms/jungle','') on conflict (bucket,storage_path) do nothing;
insert into gallery_media(gallery_id,media_id,sort_order) select g.id,m.id,6 from galleries g, media m where g.slug='collage' and m.storage_path='rooms/jungle/room-jungle-1.jpg' on conflict do nothing;
insert into media(storage_path,folder,alt) values('rooms/jungle/room-jungle-2.jpg','rooms/jungle','') on conflict (bucket,storage_path) do nothing;
insert into gallery_media(gallery_id,media_id,sort_order) select g.id,m.id,7 from galleries g, media m where g.slug='collage' and m.storage_path='rooms/jungle/room-jungle-2.jpg' on conflict do nothing;
insert into media(storage_path,folder,alt) values('rooms/loft/room-loft-1.jpg','rooms/loft','') on conflict (bucket,storage_path) do nothing;
insert into gallery_media(gallery_id,media_id,sort_order) select g.id,m.id,8 from galleries g, media m where g.slug='collage' and m.storage_path='rooms/loft/room-loft-1.jpg' on conflict do nothing;
insert into media(storage_path,folder,alt) values('rooms/loft/room-loft-2.jpg','rooms/loft','') on conflict (bucket,storage_path) do nothing;
insert into gallery_media(gallery_id,media_id,sort_order) select g.id,m.id,9 from galleries g, media m where g.slug='collage' and m.storage_path='rooms/loft/room-loft-2.jpg' on conflict do nothing;
insert into media(storage_path,folder,alt) values('activities/lava-floor/lava-pol-real-1.jpg','activities/lava-floor','') on conflict (bucket,storage_path) do nothing;
insert into gallery_media(gallery_id,media_id,sort_order) select g.id,m.id,10 from galleries g, media m where g.slug='collage' and m.storage_path='activities/lava-floor/lava-pol-real-1.jpg' on conflict do nothing;
insert into media(storage_path,folder,alt) values('activities/lava-floor/lava-pol-real-2.jpg','activities/lava-floor','') on conflict (bucket,storage_path) do nothing;
insert into gallery_media(gallery_id,media_id,sort_order) select g.id,m.id,11 from galleries g, media m where g.slug='collage' and m.storage_path='activities/lava-floor/lava-pol-real-2.jpg' on conflict do nothing;
insert into media(storage_path,folder,alt) values('activities/lava-floor/lava-pol-real-3.jpg','activities/lava-floor','') on conflict (bucket,storage_path) do nothing;
insert into gallery_media(gallery_id,media_id,sort_order) select g.id,m.id,12 from galleries g, media m where g.slug='collage' and m.storage_path='activities/lava-floor/lava-pol-real-3.jpg' on conflict do nothing;
insert into media(storage_path,folder,alt) values('activities/kuzar/kuzar-real-arena-1.jpg','activities/kuzar','') on conflict (bucket,storage_path) do nothing;
insert into gallery_media(gallery_id,media_id,sort_order) select g.id,m.id,13 from galleries g, media m where g.slug='collage' and m.storage_path='activities/kuzar/kuzar-real-arena-1.jpg' on conflict do nothing;
insert into media(storage_path,folder,alt) values('activities/kuzar/kuzar-real-arena-2.jpg','activities/kuzar','') on conflict (bucket,storage_path) do nothing;
insert into gallery_media(gallery_id,media_id,sort_order) select g.id,m.id,14 from galleries g, media m where g.slug='collage' and m.storage_path='activities/kuzar/kuzar-real-arena-2.jpg' on conflict do nothing;
insert into media(storage_path,folder,alt) values('activities/kuzar/kuzar-real-arena-3.jpg','activities/kuzar','') on conflict (bucket,storage_path) do nothing;
insert into gallery_media(gallery_id,media_id,sort_order) select g.id,m.id,15 from galleries g, media m where g.slug='collage' and m.storage_path='activities/kuzar/kuzar-real-arena-3.jpg' on conflict do nothing;
insert into galleries(slug,title) values('jungle','jungle') on conflict (slug) do nothing;
insert into media(storage_path,folder,alt) values('rooms/jungle/room-jungle-1.jpg','rooms/jungle','') on conflict (bucket,storage_path) do nothing;
insert into gallery_media(gallery_id,media_id,sort_order) select g.id,m.id,0 from galleries g, media m where g.slug='jungle' and m.storage_path='rooms/jungle/room-jungle-1.jpg' on conflict do nothing;
insert into media(storage_path,folder,alt) values('rooms/jungle/room-jungle-2.jpg','rooms/jungle','') on conflict (bucket,storage_path) do nothing;
insert into gallery_media(gallery_id,media_id,sort_order) select g.id,m.id,1 from galleries g, media m where g.slug='jungle' and m.storage_path='rooms/jungle/room-jungle-2.jpg' on conflict do nothing;
insert into media(storage_path,folder,alt) values('rooms/jungle/f6fc031b-b47f-457a-b2e5-8226815ad9c0.jpeg','rooms/jungle','') on conflict (bucket,storage_path) do nothing;
insert into gallery_media(gallery_id,media_id,sort_order) select g.id,m.id,2 from galleries g, media m where g.slug='jungle' and m.storage_path='rooms/jungle/f6fc031b-b47f-457a-b2e5-8226815ad9c0.jpeg' on conflict do nothing;
insert into media(storage_path,folder,alt) values('rooms/jungle/fe0f8752-696e-4f60-9c88-fcea23ef4103.jpeg','rooms/jungle','') on conflict (bucket,storage_path) do nothing;
insert into gallery_media(gallery_id,media_id,sort_order) select g.id,m.id,3 from galleries g, media m where g.slug='jungle' and m.storage_path='rooms/jungle/fe0f8752-696e-4f60-9c88-fcea23ef4103.jpeg' on conflict do nothing;
insert into galleries(slug,title) values('loft','loft') on conflict (slug) do nothing;
insert into media(storage_path,folder,alt) values('rooms/loft/room-loft-1.jpg','rooms/loft','') on conflict (bucket,storage_path) do nothing;
insert into gallery_media(gallery_id,media_id,sort_order) select g.id,m.id,0 from galleries g, media m where g.slug='loft' and m.storage_path='rooms/loft/room-loft-1.jpg' on conflict do nothing;
insert into media(storage_path,folder,alt) values('rooms/loft/room-loft-2.jpg','rooms/loft','') on conflict (bucket,storage_path) do nothing;
insert into gallery_media(gallery_id,media_id,sort_order) select g.id,m.id,1 from galleries g, media m where g.slug='loft' and m.storage_path='rooms/loft/room-loft-2.jpg' on conflict do nothing;
insert into media(storage_path,folder,alt) values('rooms/loft/9bf12eb4-5342-47a2-9f0c-df9f864f0405.jpeg','rooms/loft','') on conflict (bucket,storage_path) do nothing;
insert into gallery_media(gallery_id,media_id,sort_order) select g.id,m.id,2 from galleries g, media m where g.slug='loft' and m.storage_path='rooms/loft/9bf12eb4-5342-47a2-9f0c-df9f864f0405.jpeg' on conflict do nothing;
insert into media(storage_path,folder,alt) values('rooms/loft/a1f34b81-2c83-43d4-beb4-c847afdeb72c.jpeg','rooms/loft','') on conflict (bucket,storage_path) do nothing;
insert into gallery_media(gallery_id,media_id,sort_order) select g.id,m.id,3 from galleries g, media m where g.slug='loft' and m.storage_path='rooms/loft/a1f34b81-2c83-43d4-beb4-c847afdeb72c.jpeg' on conflict do nothing;
